name: Build Lambda Layer
on:
  push:
    branches:
      - main
    paths:
      - "requirements.txt"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        aws-region: ["ap-northeast-1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -t layer/python/lib/python${{ matrix.python-version }}/site-packages/
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}
      - run: sam build --use-container --parameter-overrides PythonVersion=python${{ matrix.python-version }}
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
