name: CI
on:
  push:
    branches:
      - main
    paths:
      - "requirements.txt"
permissions:
  id-token: write
  contents: read
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        aws-region: ["ap-northeast-1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -t layer/python/lib/python${{ matrix.python-version }}/site-packages/
      - name: Zip Layer
        run: |
          cd layer
          zip -r layer.zip . -x '*.pyc'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}
      - name: Publish Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name pyiceberg \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python${{ matrix.python-version }}
            --compatible-architectures "x86_64" \
            --region ${{ matrix.aws-region }}
